# Generated by Django 3.2.13 on 2022-08-04 12:53

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='We suggest to use no more than 3 tags to improve search results', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
