# Generated by Django 3.2.13 on 2022-08-04 12:58

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0002_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='We suggest to use no more than 3 tags to improve search results', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
