# Generated by Django 3.2.13 on 2022-07-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
