# Generated by Django 3.2.13 on 2022-07-24 08:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0018_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='baaaaah', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
