# Generated by Django 3.2.13 on 2022-07-24 09:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0019_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='tags must be lower case', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
