# Generated by Django 3.2.13 on 2022-07-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='list_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
