# Generated by Django 3.2.13 on 2022-07-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_list_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='list_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
