# Generated by Django 3.2.13 on 2022-07-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_post_list_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='list_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
