# Generated by Django 3.2.13 on 2022-08-02 12:29

import blog.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0027_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='list_image',
            field=models.CharField(blank=True, help_text='Paste here a link ending with .jpg .gif .png', max_length=200, null=True, validators=[blog.validators.validate_url], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='We suggest to use no more than 3 tags to improve search results', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
